### PR TITLE
Add session methods for custom interfaces

### PR DESCRIPTION
**Pull request by Antipitch**
Would allow dependency inversion and usage of custom/ consuming session interfaces within applications' internal services that deal with sessions. Right now, people have to scatter gorilla/sessions imports all over their services or define rather useless facades.

### CODE REVIEW

**Comment by elithrar** [comment]
Hi Jan,

It’s not clear that these are meaningful API/UX improvements over checking .IsNew directly or checking sessions.Values directly.

In a v2 it’s likely we’ll provide Get/Set methods & avoid direct access to underlying data types, but I don’t want to add to the API today and provide two ways to do the same thing.

**Comment by Antipitch** [comment]
Hey Matt,
as I said: right now, I'm forced to import the package and use its' session struct. Everywhere in my software. Sounds a bit harsh, but that's the opposite of loose coupling/ solid software/ dependency inversion. Testability comes on top (mock an external package instead of a simple custom interface). Also, it's an absolutely non-breaking change.

That said, would be cool if you could get include that into v2. Maybe also make the session fields private and rename `IsNew` to `new`?!

Cheers

**Comment by Antipitch** [comment]
> You don't need to import the package everywhere. You could define your own `type SessionProvider interface` and the write a simple wrapper type that fulfills the interface. Then instead of passing around a `Session` directly you just wrap it in your type before passing it in. It's only a few lines of code and doesn't require modifying the package API at all.

I perfectly know that (as said in the beginning). And I'm absolutely willing to write as many lines of code as I have to, that's not the point. But setting an imported struct's fields directly is not really an API, is it? It surely prevents interfacing right away, and that could easily be fixed. If I later decided to use a breaking change version or totally different package I could still write a "provider" or whatever you wanna call it.

**Comment by kisielk** [comment]
IMO creating methods just for the purpose of setting struct fields is pointless, unless there is some kind of transformation or validation that needs to happen. It's pretty common in Go code to just set struct fields directly, many packages including those in the standard library do this.

**Pull request closed without merging**
