### PR TITLE
Don't propagate "not exist" error if trying to erase a session matchi…

### PR DESCRIPTION
**Pull request by mariusor**
Summary of Changes

Don't consider "oserror.ErrNotExist" as a failure when trying to erase a session which corresponds to a missing file.

Hello, in the current implementation, if a request contains a session token that has been stored in a file that has been deleted and we're trying to erase it using the Options.MaxAge = -1 workaround, the action still fails, because the missing file error gets propagated higher in the stack.

This small fix prevents this, and ensures that the session is regenerated.
___

This is a reopen of #237 which was closed by the stale bot.

### CODE REVIEW

**Comment by DavidLarsKetch** [comment]
Checks out to me, I recommend this is merged in after #253

**Comment by mariusor** [comment]
Thank you for the support @DavidLarsKetch :) Are you affiliated with the project in an official capacity?

**Comment by DavidLarsKetch** [comment]
Not yet, just trying to lend a hand with review. I think @elithrar is still the only one with write permissions.

**Review by coreydaley — APPROVED** [review]

**Comment by mariusor** [comment]
Whoa! Thank you @coreydaley :partying_face:

**Pull request merged**
